// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package feeds

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FeedCreated struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedId               string   `protobuf:"bytes,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedCreated) Reset()         { *m = FeedCreated{} }
func (m *FeedCreated) String() string { return proto.CompactTextString(m) }
func (*FeedCreated) ProtoMessage()    {}
func (*FeedCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *FeedCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedCreated.Unmarshal(m, b)
}
func (m *FeedCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedCreated.Marshal(b, m, deterministic)
}
func (m *FeedCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedCreated.Merge(m, src)
}
func (m *FeedCreated) XXX_Size() int {
	return xxx_messageInfo_FeedCreated.Size(m)
}
func (m *FeedCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedCreated.DiscardUnknown(m)
}

var xxx_messageInfo_FeedCreated proto.InternalMessageInfo

func (m *FeedCreated) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FeedCreated) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

func (m *FeedCreated) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type FeedSubscribed struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedId               string   `protobuf:"bytes,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	FeedSubscriptionId   string   `protobuf:"bytes,3,opt,name=feed_subscription_id,json=feedSubscriptionId,proto3" json:"feed_subscription_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedSubscribed) Reset()         { *m = FeedSubscribed{} }
func (m *FeedSubscribed) String() string { return proto.CompactTextString(m) }
func (*FeedSubscribed) ProtoMessage()    {}
func (*FeedSubscribed) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *FeedSubscribed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedSubscribed.Unmarshal(m, b)
}
func (m *FeedSubscribed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedSubscribed.Marshal(b, m, deterministic)
}
func (m *FeedSubscribed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedSubscribed.Merge(m, src)
}
func (m *FeedSubscribed) XXX_Size() int {
	return xxx_messageInfo_FeedSubscribed.Size(m)
}
func (m *FeedSubscribed) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedSubscribed.DiscardUnknown(m)
}

var xxx_messageInfo_FeedSubscribed proto.InternalMessageInfo

func (m *FeedSubscribed) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FeedSubscribed) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

func (m *FeedSubscribed) GetFeedSubscriptionId() string {
	if m != nil {
		return m.FeedSubscriptionId
	}
	return ""
}

type FeedRefreshed struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedId               string   `protobuf:"bytes,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedRefreshed) Reset()         { *m = FeedRefreshed{} }
func (m *FeedRefreshed) String() string { return proto.CompactTextString(m) }
func (*FeedRefreshed) ProtoMessage()    {}
func (*FeedRefreshed) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *FeedRefreshed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedRefreshed.Unmarshal(m, b)
}
func (m *FeedRefreshed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedRefreshed.Marshal(b, m, deterministic)
}
func (m *FeedRefreshed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedRefreshed.Merge(m, src)
}
func (m *FeedRefreshed) XXX_Size() int {
	return xxx_messageInfo_FeedRefreshed.Size(m)
}
func (m *FeedRefreshed) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedRefreshed.DiscardUnknown(m)
}

var xxx_messageInfo_FeedRefreshed proto.InternalMessageInfo

func (m *FeedRefreshed) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FeedRefreshed) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

type FeedOptionsChanged struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedSubscriptionId   string   `protobuf:"bytes,2,opt,name=feed_subscription_id,json=feedSubscriptionId,proto3" json:"feed_subscription_id,omitempty"`
	Autopost             bool     `protobuf:"varint,3,opt,name=autopost,proto3" json:"autopost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedOptionsChanged) Reset()         { *m = FeedOptionsChanged{} }
func (m *FeedOptionsChanged) String() string { return proto.CompactTextString(m) }
func (*FeedOptionsChanged) ProtoMessage()    {}
func (*FeedOptionsChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *FeedOptionsChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedOptionsChanged.Unmarshal(m, b)
}
func (m *FeedOptionsChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedOptionsChanged.Marshal(b, m, deterministic)
}
func (m *FeedOptionsChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedOptionsChanged.Merge(m, src)
}
func (m *FeedOptionsChanged) XXX_Size() int {
	return xxx_messageInfo_FeedOptionsChanged.Size(m)
}
func (m *FeedOptionsChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedOptionsChanged.DiscardUnknown(m)
}

var xxx_messageInfo_FeedOptionsChanged proto.InternalMessageInfo

func (m *FeedOptionsChanged) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FeedOptionsChanged) GetFeedSubscriptionId() string {
	if m != nil {
		return m.FeedSubscriptionId
	}
	return ""
}

func (m *FeedOptionsChanged) GetAutopost() bool {
	if m != nil {
		return m.Autopost
	}
	return false
}

type FeedUnsubscribed struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedSubscriptionId   string   `protobuf:"bytes,2,opt,name=feed_subscription_id,json=feedSubscriptionId,proto3" json:"feed_subscription_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedUnsubscribed) Reset()         { *m = FeedUnsubscribed{} }
func (m *FeedUnsubscribed) String() string { return proto.CompactTextString(m) }
func (*FeedUnsubscribed) ProtoMessage()    {}
func (*FeedUnsubscribed) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{4}
}

func (m *FeedUnsubscribed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedUnsubscribed.Unmarshal(m, b)
}
func (m *FeedUnsubscribed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedUnsubscribed.Marshal(b, m, deterministic)
}
func (m *FeedUnsubscribed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedUnsubscribed.Merge(m, src)
}
func (m *FeedUnsubscribed) XXX_Size() int {
	return xxx_messageInfo_FeedUnsubscribed.Size(m)
}
func (m *FeedUnsubscribed) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedUnsubscribed.DiscardUnknown(m)
}

var xxx_messageInfo_FeedUnsubscribed proto.InternalMessageInfo

func (m *FeedUnsubscribed) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FeedUnsubscribed) GetFeedSubscriptionId() string {
	if m != nil {
		return m.FeedSubscriptionId
	}
	return ""
}

type PostsImported struct {
	FeedId               string   `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	PostIds              []string `protobuf:"bytes,2,rep,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsImported) Reset()         { *m = PostsImported{} }
func (m *PostsImported) String() string { return proto.CompactTextString(m) }
func (*PostsImported) ProtoMessage()    {}
func (*PostsImported) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{5}
}

func (m *PostsImported) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsImported.Unmarshal(m, b)
}
func (m *PostsImported) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsImported.Marshal(b, m, deterministic)
}
func (m *PostsImported) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsImported.Merge(m, src)
}
func (m *PostsImported) XXX_Size() int {
	return xxx_messageInfo_PostsImported.Size(m)
}
func (m *PostsImported) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsImported.DiscardUnknown(m)
}

var xxx_messageInfo_PostsImported proto.InternalMessageInfo

func (m *PostsImported) GetFeedId() string {
	if m != nil {
		return m.FeedId
	}
	return ""
}

func (m *PostsImported) GetPostIds() []string {
	if m != nil {
		return m.PostIds
	}
	return nil
}

func init() {
	proto.RegisterType((*FeedCreated)(nil), "courier.feeds.FeedCreated")
	proto.RegisterType((*FeedSubscribed)(nil), "courier.feeds.FeedSubscribed")
	proto.RegisterType((*FeedRefreshed)(nil), "courier.feeds.FeedRefreshed")
	proto.RegisterType((*FeedOptionsChanged)(nil), "courier.feeds.FeedOptionsChanged")
	proto.RegisterType((*FeedUnsubscribed)(nil), "courier.feeds.FeedUnsubscribed")
	proto.RegisterType((*PostsImported)(nil), "courier.feeds.PostsImported")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0x8b, 0xdb, 0xee, 0x68, 0x65, 0x09, 0x82, 0xd5, 0xd3, 0x92, 0xd3, 0x9e, 0x16,
	0xc1, 0x4f, 0xa0, 0x05, 0xa1, 0x27, 0xb5, 0xe2, 0x45, 0x90, 0xa5, 0xdd, 0x4c, 0xdd, 0x80, 0x36,
	0x25, 0x93, 0x78, 0xf1, 0xcb, 0xcb, 0xa4, 0xfe, 0xc1, 0xc3, 0x8a, 0xee, 0x2d, 0x2f, 0x2f, 0xf9,
	0xbd, 0xc9, 0x64, 0xe0, 0x00, 0x5f, 0xb1, 0x77, 0xb4, 0x1c, 0xac, 0x71, 0x46, 0xe4, 0x6b, 0xe3,
	0xad, 0x46, 0xbb, 0xec, 0x10, 0x15, 0xc9, 0x5b, 0xd8, 0xbf, 0x42, 0x54, 0xa5, 0xc5, 0xc6, 0xa1,
	0x12, 0xc7, 0x90, 0x7a, 0x42, 0xbb, 0xd2, 0xaa, 0x88, 0xe6, 0xd1, 0x62, 0x5a, 0x4f, 0x58, 0x56,
	0xc1, 0xe0, 0x0b, 0x6c, 0xc4, 0xa3, 0xc1, 0xb2, 0x52, 0x62, 0x06, 0x89, 0xb7, 0xcf, 0x45, 0x12,
	0x36, 0x79, 0x29, 0x1d, 0x1c, 0x32, 0xf2, 0xce, 0xb7, 0xb4, 0xb6, 0xba, 0xdd, 0x89, 0x7a, 0x06,
	0x47, 0xc1, 0xa0, 0x11, 0x32, 0x38, 0x6d, 0x7a, 0x3e, 0x35, 0xc6, 0x88, 0xee, 0x9b, 0x1f, 0xac,
	0x4a, 0xc9, 0x0b, 0xc8, 0x39, 0xb5, 0xc6, 0xce, 0x22, 0x6d, 0x76, 0x09, 0x95, 0x6f, 0x20, 0x18,
	0x71, 0x1d, 0x90, 0x54, 0x6e, 0x9a, 0xfe, 0xe9, 0x37, 0xce, 0xb6, 0x1a, 0xe3, 0x6d, 0x35, 0x8a,
	0x53, 0xc8, 0x1a, 0xef, 0xcc, 0x60, 0xc8, 0x85, 0x97, 0x64, 0xf5, 0x97, 0x96, 0x8f, 0x30, 0xe3,
	0xf0, 0xfb, 0x9e, 0xfe, 0xd0, 0xb7, 0x7f, 0x47, 0xcb, 0x12, 0xf2, 0x1b, 0x43, 0x8e, 0xaa, 0x97,
	0xc1, 0xd8, 0x8f, 0x9f, 0xfe, 0xec, 0x42, 0xf4, 0xa3, 0xf5, 0x27, 0x90, 0x71, 0x41, 0x2b, 0xad,
	0xa8, 0x88, 0xe7, 0xc9, 0x62, 0x5a, 0xa7, 0xac, 0x2b, 0x45, 0x97, 0xe9, 0xc3, 0x5e, 0x98, 0x9a,
	0x76, 0x12, 0x66, 0xe9, 0xfc, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x2a, 0x7d, 0xcf, 0x5b, 0x02,
	0x00, 0x00,
}
