// Auto-generated by relay-compiler. Do not edit.

import Relay

struct DetailedTweetActions_tweetGroup {
    var node: ReaderFragment {
        ReaderFragment(
            name: "DetailedTweetActions_tweetGroup",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "status"
                ))
            ])
    }
}


extension DetailedTweetActions_tweetGroup {
    struct Data: Readable {
        var id: String
        var status: TweetStatus

        init(from data: SelectorData) {
            id = data.get(String.self, "id")
            status = data.get(TweetStatus.self, "status")
        }
    }
}

protocol DetailedTweetActions_tweetGroup_Key {
    var fragment_DetailedTweetActions_tweetGroup: FragmentPointer { get }
}

extension DetailedTweetActions_tweetGroup {
    func getFragmentPointer(_ key: DetailedTweetActions_tweetGroup_Key) -> FragmentPointer {
        key.fragment_DetailedTweetActions_tweetGroup
    }
}

extension DetailedTweetActions_tweetGroup: Relay.Fragment {}
