// Auto-generated by relay-compiler. Do not edit.

import Relay

struct SubscriptionSection_user {
    var node: ReaderFragment {
        ReaderFragment(
            name: "SubscriptionSection_user",
            selections: [
                .field(ReaderLinkedField(
                    name: "customer",
                    concreteType: "Customer",
                    plural: false,
                    selections: [
                        .field(ReaderLinkedField(
                            name: "creditCard",
                            concreteType: "CreditCard",
                            plural: false,
                            selections: [
                                .field(ReaderScalarField(
                                    name: "brand"
                                )),
                                .field(ReaderScalarField(
                                    name: "lastFour"
                                ))
                            ]
                        ))
                    ]
                )),
                .field(ReaderLinkedField(
                    name: "subscription",
                    concreteType: "UserSubscription",
                    plural: false,
                    selections: [
                        .field(ReaderScalarField(
                            name: "status"
                        )),
                        .field(ReaderScalarField(
                            name: "periodEnd"
                        ))
                    ]
                )),
                .field(ReaderScalarField(
                    name: "subscriptionStatusOverride"
                ))
            ])
    }
}


extension SubscriptionSection_user {
    struct Data: Readable {
        var customer: Customer_customer?
        var subscription: UserSubscription_subscription?
        var subscriptionStatusOverride: SubscriptionStatus?

        init(from data: SelectorData) {
            customer = data.get(Customer_customer?.self, "customer")
            subscription = data.get(UserSubscription_subscription?.self, "subscription")
            subscriptionStatusOverride = data.get(SubscriptionStatus?.self, "subscriptionStatusOverride")
        }

        struct Customer_customer: Readable {
            var creditCard: CreditCard_creditCard?

            init(from data: SelectorData) {
                creditCard = data.get(CreditCard_creditCard?.self, "creditCard")
            }

            struct CreditCard_creditCard: Readable {
                var brand: String
                var lastFour: String

                init(from data: SelectorData) {
                    brand = data.get(String.self, "brand")
                    lastFour = data.get(String.self, "lastFour")
                }
            }
        }

        struct UserSubscription_subscription: Readable {
            var status: SubscriptionStatus
            var periodEnd: String

            init(from data: SelectorData) {
                status = data.get(SubscriptionStatus.self, "status")
                periodEnd = data.get(String.self, "periodEnd")
            }
        }
    }
}

protocol SubscriptionSection_user_Key {
    var fragment_SubscriptionSection_user: FragmentPointer { get }
}

extension SubscriptionSection_user {
    func getFragmentPointer(_ key: SubscriptionSection_user_Key) -> FragmentPointer {
        key.fragment_SubscriptionSection_user
    }
}

enum SubscriptionStatus: String, Hashable, VariableValueConvertible, ReadableScalar, CustomStringConvertible {
    case active = "ACTIVE"
    case canceled = "CANCELED"
    case expired = "EXPIRED"
    case inactive = "INACTIVE"

    var description: String { rawValue }
}

extension SubscriptionSection_user: Relay.Fragment {}
