// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct DeleteFeedMutation {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "DeleteFeedMutation",
                type: "Mutation",
                selections: [
                    .field(ReaderLinkedField(
                        name: "deleteFeed",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "DeleteFeedPayload",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "DeleteFeedMutation",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "deleteFeed",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "DeleteFeedPayload",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "DeleteFeedMutation",
                operationKind: .mutation,
                text: """
mutation DeleteFeedMutation(
  $input: DeleteFeedInput!
) {
  deleteFeed(input: $input) {
    id
  }
}
"""
            )
        )
    }
}

extension DeleteFeedMutation {
    public struct Variables: VariableDataConvertible {
        public var input: DeleteFeedInput

        public init(input: DeleteFeedInput) {
            self.input = input
        }

        public var variableData: VariableData {
            [
                "input": input
            ]
        }
    }

    public init(input: DeleteFeedInput) {
        self.init(variables: .init(input: input))
    }
}

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.Query.WrappedValue where O == DeleteFeedMutation {
    public func get(input: DeleteFeedInput, fetchKey: Any? = nil) -> RelaySwiftUI.Query<DeleteFeedMutation>.Result {
        self.get(.init(input: input), fetchKey: fetchKey)
    }
}
#endif

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.RefetchableFragment.Wrapper where F.Operation == DeleteFeedMutation {
    public func refetch(input: DeleteFeedInput) {
        self.refetch(.init(input: input))
    }
}
#endif

public struct DeleteFeedInput: VariableDataConvertible {
    public var id: String

    public init(id: String) {
        self.id = id
    }

    public var variableData: VariableData {
        [
            "id": id
        ]
    }
}


extension DeleteFeedMutation {
    public struct Data: Decodable {
        public var deleteFeed: DeleteFeedPayload_deleteFeed

        public struct DeleteFeedPayload_deleteFeed: Decodable, Identifiable {
            public var id: String
        }
    }
}

extension DeleteFeedMutation: Relay.Operation {}