// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct DetailedTweetActions_tweetGroup {
    public var fragmentPointer: FragmentPointer

    public init(key: DetailedTweetActions_tweetGroup_Key) {
        fragmentPointer = key.fragment_DetailedTweetActions_tweetGroup
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "DetailedTweetActions_tweetGroup",
            type: "TweetGroup",
            selections: [
                .field(ReaderLinkedField(
                    name: "tweets",
                    concreteType: "Tweet",
                    plural: true,
                    selections: [
                        .field(ReaderScalarField(
                            name: "postedTweetID"
                        ))
                    ]
                )),
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "status"
                )),
                .field(ReaderScalarField(
                    name: "postAfter"
                )),
                .field(ReaderScalarField(
                    name: "postedAt"
                )),
                .field(ReaderScalarField(
                    name: "postedRetweetID"
                ))
            ]
        )
    }
}

extension DetailedTweetActions_tweetGroup {
    public struct Data: Decodable, Identifiable {
        public var tweets: [Tweet_tweets]
        public var id: String
        public var status: TweetStatus
        public var postAfter: String?
        public var postedAt: String?
        public var postedRetweetID: String?

        public struct Tweet_tweets: Decodable {
            public var postedTweetID: String?
        }
    }
}

public protocol DetailedTweetActions_tweetGroup_Key {
    var fragment_DetailedTweetActions_tweetGroup: FragmentPointer { get }
}
extension DetailedTweetActions_tweetGroup: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI
extension DetailedTweetActions_tweetGroup_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<DetailedTweetActions_tweetGroup> {
        RelaySwiftUI.FragmentNext<DetailedTweetActions_tweetGroup>(self)
    }
}
#endif