// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct DetailedTweetRow_tweet {
    public var fragmentPointer: FragmentPointer

    public init(key: DetailedTweetRow_tweet_Key) {
        fragmentPointer = key.fragment_DetailedTweetRow_tweet
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "DetailedTweetRow_tweet",
            type: "Tweet",
            selections: [
                .field(ReaderScalarField(
                    name: "body"
                )),
                .field(ReaderScalarField(
                    name: "mediaURLs"
                ))
            ]
        )
    }
}

extension DetailedTweetRow_tweet {
    public struct Data: Decodable {
        public var body: String
        public var mediaURLs: [String]
    }
}

public protocol DetailedTweetRow_tweet_Key {
    var fragment_DetailedTweetRow_tweet: FragmentPointer { get }
}

extension DetailedTweetRow_tweet: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension DetailedTweetRow_tweet_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<DetailedTweetRow_tweet> {
        RelaySwiftUI.FragmentNext<DetailedTweetRow_tweet>(self)
    }
}
#endif