// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct EditTweetForm_tweetGroup {
    public var fragmentPointer: FragmentPointer

    public init(key: EditTweetForm_tweetGroup_Key) {
        fragmentPointer = key.fragment_EditTweetForm_tweetGroup
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "EditTweetForm_tweetGroup",
            type: "TweetGroup",
            selections: [
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderLinkedField(
                    name: "tweets",
                    concreteType: "Tweet",
                    plural: true,
                    selections: [
                        .field(ReaderScalarField(
                            name: "body"
                        )),
                        .field(ReaderScalarField(
                            name: "mediaURLs"
                        ))
                    ]
                ))
            ]
        )
    }
}

extension EditTweetForm_tweetGroup {
    public struct Data: Decodable, Identifiable {
        public var id: String
        public var tweets: [Tweet_tweets]

        public struct Tweet_tweets: Decodable {
            public var body: String
            public var mediaURLs: [String]
        }
    }
}

public protocol EditTweetForm_tweetGroup_Key {
    var fragment_EditTweetForm_tweetGroup: FragmentPointer { get }
}

extension EditTweetForm_tweetGroup: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension EditTweetForm_tweetGroup_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    public func asFragment() -> RelaySwiftUI.FragmentNext<EditTweetForm_tweetGroup> {
        RelaySwiftUI.FragmentNext<EditTweetForm_tweetGroup>(self)
    }
}
#endif