// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct EditTweetMutation {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "EditTweetMutation",
                type: "Mutation",
                selections: [
                    .field(ReaderLinkedField(
                        name: "editTweet",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "EditTweetPayload",
                        plural: false,
                        selections: [
                            .field(ReaderLinkedField(
                                name: "tweetGroup",
                                concreteType: "TweetGroup",
                                plural: false,
                                selections: [
                                    .field(ReaderScalarField(
                                        name: "id"
                                    )),
                                    .field(ReaderLinkedField(
                                        name: "tweets",
                                        concreteType: "Tweet",
                                        plural: true,
                                        selections: [
                                            .field(ReaderScalarField(
                                                name: "body"
                                            )),
                                            .field(ReaderScalarField(
                                                name: "mediaURLs"
                                            ))
                                        ]
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "EditTweetMutation",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "editTweet",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "EditTweetPayload",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "tweetGroup",
                                concreteType: "TweetGroup",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "id"
                                    )),
                                    .field(NormalizationLinkedField(
                                        name: "tweets",
                                        concreteType: "Tweet",
                                        plural: true,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "body"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "mediaURLs"
                                            ))
                                        ]
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "EditTweetMutation",
                operationKind: .mutation,
                text: """
mutation EditTweetMutation(
  $input: EditTweetInput!
) {
  editTweet(input: $input) {
    tweetGroup {
      id
      tweets {
        body
        mediaURLs
      }
    }
  }
}
"""
            )
        )
    }
}

extension EditTweetMutation {
    public struct Variables: VariableDataConvertible {
        public var input: EditTweetInput

        public init(input: EditTweetInput) {
            self.input = input
        }

        public var variableData: VariableData {
            [
                "input": input
            ]
        }
    }

    public init(input: EditTweetInput) {
        self.init(variables: .init(input: input))
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)extension RelaySwiftUI.QueryNext.WrappedValue where O == EditTweetMutation {
    public func get(input: EditTweetInput, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<EditTweetMutation>.Result {
        self.get(.init(input: input), fetchKey: fetchKey)
    }
}
#endif

public struct EditTweetInput: VariableDataConvertible {
    public var id: String
    public var tweets: [TweetEdit]

    public init(id: String, tweets: [TweetEdit]) {
        self.id = id
        self.tweets = tweets
    }

    public var variableData: VariableData {
        [
            "id": id,
            "tweets": tweets
        ]
    }
}


public struct TweetEdit: VariableDataConvertible {
    public var body: String
    public var mediaURLs: [String]?

    public init(body: String, mediaURLs: [String]? = nil) {
        self.body = body
        self.mediaURLs = mediaURLs
    }

    public var variableData: VariableData {
        [
            "body": body,
            "mediaURLs": mediaURLs
        ]
    }
}

extension EditTweetMutation {
    public struct Data: Decodable {
        public var editTweet: EditTweetPayload_editTweet

        public struct EditTweetPayload_editTweet: Decodable {
            public var tweetGroup: TweetGroup_tweetGroup

            public struct TweetGroup_tweetGroup: Decodable, Identifiable {
                public var id: String
                public var tweets: [Tweet_tweets]

                public struct Tweet_tweets: Decodable {
                    public var body: String
                    public var mediaURLs: [String]
                }
            }
        }
    }
}
extension EditTweetMutation: Relay.Operation {}