// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct FeedsSectionPreviewQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "FeedsSectionPreviewQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "FeedsSection_feeds"
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "FeedsSectionPreviewQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "allFeeds",
                                args: [
                                    LiteralArgument(name: "first", value: 10)
                                ],
                                storageKey: "allFeeds(first:10)",
                                concreteType: "FeedConnection",
                                plural: false,
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "edges",
                                        concreteType: "FeedEdge",
                                        plural: true,
                                        selections: [
                                            .field(NormalizationLinkedField(
                                                name: "node",
                                                concreteType: "Feed",
                                                plural: false,
                                                selections: [
                                                    .field(NormalizationScalarField(
                                                        name: "id"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "title"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "homePageURL"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "refreshedAt"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "refreshing"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "autopost"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "__typename"
                                                    ))
                                                ]
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "cursor"
                                            ))
                                        ]
                                    )),
                                    .field(NormalizationLinkedField(
                                        name: "pageInfo",
                                        concreteType: "PageInfo",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "endCursor"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "hasNextPage"
                                            ))
                                        ]
                                    ))
                                ]
                            )),
                            .handle(NormalizationHandle(
                                kind: .linked,
                                name: "allFeeds",
                                args: [
                                    LiteralArgument(name: "first", value: 10)
                                ],
                                handle: "connection",
                                key: "FeedsSection_allFeeds"
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "FeedsSectionPreviewQuery",
                operationKind: .query,
                text: """
query FeedsSectionPreviewQuery {
  viewer {
    ...FeedsSection_feeds
  }
}

fragment FeedRow_feed on Feed {
  id
  title
  homePageURL
  refreshedAt
  refreshing
  autopost
}

fragment FeedsSection_feeds on Viewer {
  allFeeds(first: 10) {
    edges {
      node {
        id
        ...FeedRow_feed
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
"""
            )
        )
    }
}

extension FeedsSectionPreviewQuery {
    public typealias Variables = EmptyVariables
}



extension FeedsSectionPreviewQuery {
    public struct Data: Decodable {
        public var viewer: Viewer_viewer?

        public struct Viewer_viewer: Decodable, FeedsSection_feeds_Key {
            public var fragment_FeedsSection_feeds: FragmentPointer
        }
    }
}

extension FeedsSectionPreviewQuery: Relay.Operation {}