// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct FeedPostsSection_posts {
    public var fragmentPointer: FragmentPointer

    public init(key: FeedPostsSection_posts_Key) {
        fragmentPointer = key.fragment_FeedPostsSection_posts
    }

    public static var node: ReaderFragment {
        ReaderFragment(
            name: "FeedPostsSection_posts",
            type: "Feed",
            selections: [
                .field(ReaderLinkedField(
                    name: "__FeedPostsSection_posts_connection",
                    alias: "posts",
                    concreteType: "PostConnection",
                    plural: false,
                    selections: [
                        .field(ReaderLinkedField(
                            name: "edges",
                            concreteType: "PostEdge",
                            plural: true,
                            selections: [
                                .field(ReaderLinkedField(
                                    name: "node",
                                    concreteType: "Post",
                                    plural: false,
                                    selections: [
                                        .field(ReaderScalarField(
                                            name: "id"
                                        )),
                                        .field(ReaderScalarField(
                                            name: "__typename"
                                        )),
                                        .fragmentSpread(ReaderFragmentSpread(
                                            name: "FeedPostRow_post"
                                        ))
                                    ]
                                )),
                                .field(ReaderScalarField(
                                    name: "cursor"
                                ))
                            ]
                        )),
                        .field(ReaderLinkedField(
                            name: "pageInfo",
                            concreteType: "PageInfo",
                            plural: false,
                            selections: [
                                .field(ReaderScalarField(
                                    name: "endCursor"
                                )),
                                .field(ReaderScalarField(
                                    name: "hasNextPage"
                                ))
                            ]
                        ))
                    ]
                )),
                .field(ReaderScalarField(
                    name: "id"
                ))
            ]
        )
    }
}

extension FeedPostsSection_posts {
    public struct Data: Decodable {
        public var posts: PostConnection_posts
        public var id: String?

        public struct PostConnection_posts: Decodable, ConnectionCollection {
            public var edges: [PostEdge_edges]

            public struct PostEdge_edges: Decodable, ConnectionEdge {
                public var node: Post_node

                public struct Post_node: Decodable, Identifiable, FeedPostRow_post_Key, ConnectionNode {
                    public var id: String
                    public var fragment_FeedPostRow_post: FragmentPointer
                }
            }
        }
    }
}

public protocol FeedPostsSection_posts_Key {
    var fragment_FeedPostsSection_posts: FragmentPointer { get }
}

extension FeedPostsSection_posts: Relay.Fragment {}

extension FeedPostsSection_posts: Relay.PaginationFragment {
    public typealias Operation = FeedPostsSectionPaginationQuery
    public static var metadata: Metadata {
        RefetchMetadata(
            path: ["node"],
            identifierField: "id",
            operation: Operation.self,
            connection: ConnectionMetadata(
                path: ["posts"],
                forward: ConnectionVariableConfig(count: "count", cursor: "cursor")
            )
        )
    }
}

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension FeedPostsSection_posts_Key {
    public func asFragment() -> RelaySwiftUI.Fragment<FeedPostsSection_posts> {
        RelaySwiftUI.Fragment<FeedPostsSection_posts>(self)
    }

    public func asFragment() -> RelaySwiftUI.RefetchableFragment<FeedPostsSection_posts> {
        RelaySwiftUI.RefetchableFragment<FeedPostsSection_posts>(self)
    }

    public func asFragment() -> RelaySwiftUI.PaginationFragment<FeedPostsSection_posts> {
        RelaySwiftUI.PaginationFragment<FeedPostsSection_posts>(self)
    }
}
#endif