// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct FeedPostsSectionPaginationQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "FeedPostsSectionPaginationQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "node",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        plural: false,
                        selections: [
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "FeedPostsSection_posts",
                                args: [
                                    VariableArgument(name: "count", variableName: "count"),
                                    VariableArgument(name: "cursor", variableName: "cursor"),
                                    VariableArgument(name: "filter", variableName: "filter")
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "FeedPostsSectionPaginationQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "node",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "__typename"
                            )),
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .inlineFragment(NormalizationInlineFragment(
                                type: "Feed",
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "posts",
                                        args: [
                                            VariableArgument(name: "after", variableName: "cursor"),
                                            VariableArgument(name: "first", variableName: "count")
                                        ],
                                        concreteType: "PostConnection",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationLinkedField(
                                                name: "edges",
                                                concreteType: "PostEdge",
                                                plural: true,
                                                selections: [
                                                    .field(NormalizationLinkedField(
                                                        name: "node",
                                                        concreteType: "Post",
                                                        plural: false,
                                                        selections: [
                                                            .field(NormalizationScalarField(
                                                                name: "id"
                                                            )),
                                                            .field(NormalizationScalarField(
                                                                name: "url"
                                                            )),
                                                            .field(NormalizationScalarField(
                                                                name: "title"
                                                            )),
                                                            .field(NormalizationScalarField(
                                                                name: "htmlContent"
                                                            )),
                                                            .field(NormalizationScalarField(
                                                                name: "publishedAt"
                                                            )),
                                                            .field(NormalizationScalarField(
                                                                name: "__typename"
                                                            ))
                                                        ]
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "cursor"
                                                    ))
                                                ]
                                            )),
                                            .field(NormalizationLinkedField(
                                                name: "pageInfo",
                                                concreteType: "PageInfo",
                                                plural: false,
                                                selections: [
                                                    .field(NormalizationScalarField(
                                                        name: "endCursor"
                                                    )),
                                                    .field(NormalizationScalarField(
                                                        name: "hasNextPage"
                                                    ))
                                                ]
                                            ))
                                        ]
                                    )),
                                    .handle(NormalizationHandle(
                                        kind: .linked,
                                        name: "posts",
                                        args: [
                                            VariableArgument(name: "after", variableName: "cursor"),
                                            VariableArgument(name: "first", variableName: "count")
                                        ],
                                        handle: "connection",
                                        key: "FeedPostsSection_posts"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "FeedPostsSectionPaginationQuery",
                operationKind: .query,
                text: """
query FeedPostsSectionPaginationQuery(
  $count: Int = 10
  $cursor: Cursor
  $id: ID!
) {
  node(id: $id) {
    __typename
    ...FeedPostsSection_posts_3KQYpM
    id
  }
}

fragment FeedPostRow_post on Post {
  id
  url
  title
  htmlContent
  publishedAt
}

fragment FeedPostsSection_posts_3KQYpM on Feed {
  posts(first: $count, after: $cursor) {
    edges {
      node {
        id
        ...FeedPostRow_post
        __typename
      }
      cursor
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
  id
}
"""
            )
        )
    }
}

extension FeedPostsSectionPaginationQuery {
    public struct Variables: VariableDataConvertible {
        public var filter: TweetFilter?
        public var count: Int?
        public var cursor: String?
        public var id: String

        public init(filter: TweetFilter? = nil, count: Int? = nil, cursor: String? = nil, id: String) {
            self.filter = filter
            self.count = count
            self.cursor = cursor
            self.id = id
        }

        public var variableData: VariableData {
            [
                "filter": filter,
                "count": count,
                "cursor": cursor,
                "id": id
            ]
        }
    }

    public init(filter: TweetFilter? = nil, count: Int? = nil, cursor: String? = nil, id: String) {
        self.init(variables: .init(filter: filter, count: count, cursor: cursor, id: id))
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
extension RelaySwiftUI.QueryNext.WrappedValue where O == FeedPostsSectionPaginationQuery {
    public func get(filter: TweetFilter? = nil, count: Int? = nil, cursor: String? = nil, id: String, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<FeedPostsSectionPaginationQuery>.Result {
        self.get(.init(filter: filter, count: count, cursor: cursor, id: id), fetchKey: fetchKey)
    }
}
#endif

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
extension RelaySwiftUI.RefetchableFragment.Wrapper where F.Operation == FeedPostsSectionPaginationQuery {
    public func refetch(filter: TweetFilter? = nil, count: Int? = nil, cursor: String? = nil, id: String) {
        self.refetch(.init(filter: filter, count: count, cursor: cursor, id: id))
    }
}
#endif

extension FeedPostsSectionPaginationQuery {
    public struct Data: Decodable {
        public var node: Node_node?

        public struct Node_node: Decodable, FeedPostsSection_posts_Key {
            public var fragment_FeedPostsSection_posts: FragmentPointer
        }
    }
}

extension FeedPostsSectionPaginationQuery: Relay.Operation {}