// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct SetFeedOptionsMutation {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "SetFeedOptionsMutation",
                type: "Mutation",
                selections: [
                    .field(ReaderLinkedField(
                        name: "setFeedOptions",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "SetFeedOptionsPayload",
                        plural: false,
                        selections: [
                            .field(ReaderLinkedField(
                                name: "feed",
                                concreteType: "Feed",
                                plural: false,
                                selections: [
                                    .field(ReaderScalarField(
                                        name: "id"
                                    )),
                                    .field(ReaderScalarField(
                                        name: "autopost"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "SetFeedOptionsMutation",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "setFeedOptions",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "SetFeedOptionsPayload",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "feed",
                                concreteType: "Feed",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "id"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "autopost"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "SetFeedOptionsMutation",
                operationKind: .mutation,
                text: """
mutation SetFeedOptionsMutation(
  $input: SetFeedOptionsInput!
) {
  setFeedOptions(input: $input) {
    feed {
      id
      autopost
    }
  }
}
"""
            )
        )
    }
}

extension SetFeedOptionsMutation {
    public struct Variables: VariableDataConvertible {
        public var input: SetFeedOptionsInput

        public init(input: SetFeedOptionsInput) {
            self.input = input
        }

        public var variableData: VariableData {
            [
                "input": input
            ]
        }
    }

    public init(input: SetFeedOptionsInput) {
        self.init(variables: .init(input: input))
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
extension RelaySwiftUI.QueryNext.WrappedValue where O == SetFeedOptionsMutation {
    public func get(input: SetFeedOptionsInput, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<SetFeedOptionsMutation>.Result {
        self.get(.init(input: input), fetchKey: fetchKey)
    }
}
#endif

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
extension RelaySwiftUI.RefetchableFragment.Wrapper where F.Operation == SetFeedOptionsMutation {
    public func refetch(input: SetFeedOptionsInput) {
        self.refetch(.init(input: input))
    }
}
#endif

public struct SetFeedOptionsInput: VariableDataConvertible {
    public var id: String
    public var autopost: Bool?

    public init(id: String, autopost: Bool? = nil) {
        self.id = id
        self.autopost = autopost
    }

    public var variableData: VariableData {
        [
            "id": id,
            "autopost": autopost
        ]
    }
}


extension SetFeedOptionsMutation {
    public struct Data: Decodable {
        public var setFeedOptions: SetFeedOptionsPayload_setFeedOptions

        public struct SetFeedOptionsPayload_setFeedOptions: Decodable {
            public var feed: Feed_feed

            public struct Feed_feed: Decodable, Identifiable {
                public var id: String
                public var autopost: Bool
            }
        }
    }
}

extension SetFeedOptionsMutation: Relay.Operation {}