// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct SettingsScreenQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "SettingsScreenQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "UserProfileSection_user"
                            )),
                            .fragmentSpread(ReaderFragmentSpread(
                                name: "SubscriptionSection_user"
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "SettingsScreenQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "viewer",
                        concreteType: "Viewer",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "name"
                            )),
                            .field(NormalizationScalarField(
                                name: "picture"
                            )),
                            .field(NormalizationLinkedField(
                                name: "customer",
                                concreteType: "Customer",
                                plural: false,
                                selections: [
                                    .field(NormalizationLinkedField(
                                        name: "creditCard",
                                        concreteType: "CreditCard",
                                        plural: false,
                                        selections: [
                                            .field(NormalizationScalarField(
                                                name: "brand"
                                            )),
                                            .field(NormalizationScalarField(
                                                name: "lastFour"
                                            ))
                                        ]
                                    ))
                                ]
                            )),
                            .field(NormalizationLinkedField(
                                name: "subscription",
                                concreteType: "UserSubscription",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "status"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "periodEnd"
                                    ))
                                ]
                            )),
                            .field(NormalizationScalarField(
                                name: "subscriptionStatusOverride"
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "SettingsScreenQuery",
                operationKind: .query,
                text: """
query SettingsScreenQuery {
  viewer {
    ...UserProfileSection_user
    ...SubscriptionSection_user
  }
}

fragment SubscriptionSection_user on Viewer {
  customer {
    creditCard {
      brand
      lastFour
    }
  }
  subscription {
    status
    periodEnd
  }
  subscriptionStatusOverride
}

fragment UserProfileSection_user on Viewer {
  name
  picture
}
"""
            )
        )
    }
}

extension SettingsScreenQuery {
    public typealias Variables = EmptyVariables
}

extension SettingsScreenQuery {
    public struct Data: Decodable {
        public var viewer: Viewer_viewer?

        public struct Viewer_viewer: Decodable, UserProfileSection_user_Key, SubscriptionSection_user_Key {
            public var fragment_UserProfileSection_user: FragmentPointer
            public var fragment_SubscriptionSection_user: FragmentPointer
        }
    }
}
extension SettingsScreenQuery: Relay.Operation {}