// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct TweetCanceledEventQuery {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "TweetCanceledEventQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .field(ReaderScalarField(
                                name: "status"
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "TweetCanceledEventQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationScalarField(
                                name: "status"
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "TweetCanceledEventQuery",
                operationKind: .query,
                text: """
query TweetCanceledEventQuery(
  $id: ID!
) {
  tweetGroup(id: $id) {
    id
    status
  }
}
"""
            )
        )
    }
}

extension TweetCanceledEventQuery {
    public struct Variables: VariableDataConvertible {
        public var id: String

        public init(id: String) {
            self.id = id
        }

        public var variableData: VariableData {
            [
                "id": id
            ]
        }
    }

    public init(id: String) {
        self.init(variables: .init(id: id))
    }
}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)extension RelaySwiftUI.QueryNext.WrappedValue where O == TweetCanceledEventQuery {
    public func get(id: String, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<TweetCanceledEventQuery>.Result {
        self.get(.init(id: id), fetchKey: fetchKey)
    }
}
#endif
extension TweetCanceledEventQuery {
    public struct Data: Decodable {
        public var tweetGroup: TweetGroup_tweetGroup?

        public struct TweetGroup_tweetGroup: Decodable, Identifiable {
            public var id: String
            public var status: TweetStatus
        }
    }
}
extension TweetCanceledEventQuery: Relay.Operation {}