// Auto-generated by relay-compiler. Do not edit.

import Relay

public struct UncancelTweetMutation {
    public var variables: Variables

    public init(variables: Variables) {
        self.variables = variables
    }

    public static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "UncancelTweetMutation",
                type: "Mutation",
                selections: [
                    .field(ReaderLinkedField(
                        name: "uncancelTweet",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "UncancelTweetPayload",
                        plural: false,
                        selections: [
                            .field(ReaderLinkedField(
                                name: "tweetGroup",
                                concreteType: "TweetGroup",
                                plural: false,
                                selections: [
                                    .field(ReaderScalarField(
                                        name: "id"
                                    )),
                                    .field(ReaderScalarField(
                                        name: "status"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            operation: NormalizationOperation(
                name: "UncancelTweetMutation",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "uncancelTweet",
                        args: [
                            VariableArgument(name: "input", variableName: "input")
                        ],
                        concreteType: "UncancelTweetPayload",
                        plural: false,
                        selections: [
                            .field(NormalizationLinkedField(
                                name: "tweetGroup",
                                concreteType: "TweetGroup",
                                plural: false,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "id"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "status"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]
            ),
            params: RequestParameters(
                name: "UncancelTweetMutation",
                operationKind: .mutation,
                text: """
mutation UncancelTweetMutation(
  $input: UncancelTweetInput!
) {
  uncancelTweet(input: $input) {
    tweetGroup {
      id
      status
    }
  }
}
"""
            )
        )
    }
}

extension UncancelTweetMutation {
    public struct Variables: VariableDataConvertible {
        public var input: UncancelTweetInput

        public init(input: UncancelTweetInput) {
            self.input = input
        }

        public var variableData: VariableData {
            [
                "input": input
            ]
        }
    }

    public init(input: UncancelTweetInput) {
        self.init(variables: .init(input: input))
    }
}

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.Query.WrappedValue where O == UncancelTweetMutation {
    public func get(input: UncancelTweetInput, fetchKey: Any? = nil) -> RelaySwiftUI.Query<UncancelTweetMutation>.Result {
        self.get(.init(input: input), fetchKey: fetchKey)
    }
}
#endif

#if canImport(RelaySwiftUI)
import RelaySwiftUI

extension RelaySwiftUI.RefetchableFragment.Wrapper where F.Operation == UncancelTweetMutation {
    public func refetch(input: UncancelTweetInput) {
        self.refetch(.init(input: input))
    }
}
#endif

public struct UncancelTweetInput: VariableDataConvertible {
    public var id: String

    public init(id: String) {
        self.id = id
    }

    public var variableData: VariableData {
        [
            "id": id
        ]
    }
}


extension UncancelTweetMutation {
    public struct Data: Decodable {
        public var uncancelTweet: UncancelTweetPayload_uncancelTweet

        public struct UncancelTweetPayload_uncancelTweet: Decodable {
            public var tweetGroup: TweetGroup_tweetGroup

            public struct TweetGroup_tweetGroup: Decodable, Identifiable {
                public var id: String
                public var status: TweetStatus
            }
        }
    }
}

public enum TweetStatus: String, Decodable, Hashable, VariableValueConvertible, ReadableScalar, CustomStringConvertible {
    case draft = "DRAFT"
    case canceled = "CANCELED"
    case posted = "POSTED"
    public var description: String {
        rawValue
    }
}

extension UncancelTweetMutation: Relay.Operation {}