version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Now CLI
          command: sudo npm install -g now
      - run:
          name: Deploy to Now
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              now --token $NOW_TOKEN
            else
              now --token $NOW_TOKEN --target staging
            fi
workflows:
  version: 2
  release:
    jobs:
      - deploy
