// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package stripecb

import (
	"github.com/mjm/courier-js/internal/auth"
	"github.com/mjm/courier-js/internal/billing"
	"github.com/mjm/courier-js/internal/config"
	"github.com/mjm/courier-js/internal/event"
	billing2 "github.com/mjm/courier-js/internal/read/billing"
	"github.com/mjm/courier-js/internal/secret"
)

// Injectors from wire.go:

func InitializeLambda() (*Handler, error) {
	defaultEnv := &config.DefaultEnv{}
	awsSecretKeeper, err := secret.NewAWSSecretKeeper()
	if err != nil {
		return nil, err
	}
	loader := config.NewLoader(defaultEnv, awsSecretKeeper)
	billingConfig, err := billing.NewConfig(loader)
	if err != nil {
		return nil, err
	}
	sqsPublisherConfig, err := event.NewSQSPublisherConfig(loader)
	if err != nil {
		return nil, err
	}
	sqsPublisher, err := event.NewSQSPublisher(sqsPublisherConfig)
	if err != nil {
		return nil, err
	}
	api := billing.NewClient(billingConfig)
	authConfig, err := auth.NewConfig(loader)
	if err != nil {
		return nil, err
	}
	management, err := auth.NewManagementClient(authConfig)
	if err != nil {
		return nil, err
	}
	subscriptionQueries := billing2.NewSubscriptionQueries(api, management)
	handler := NewHandler(billingConfig, sqsPublisher, subscriptionQueries)
	return handler, nil
}
