import SwiftUI
import RelaySwiftUI

private let tweetsFragment = graphql("""
fragment TweetsList_tweets on Viewer
  @refetchable(queryName: "TweetsListPaginationQuery")
  @argumentDefinitions(
    filter: { type: "TweetFilter" }
    count: { type: "Int", defaultValue: 10 }
    cursor: { type: "Cursor" }
  ) {
  allTweets(filter: $filter, first: $count, after: $cursor)
    @connection(key: "TweetsList_allTweets") {
    edges {
      node {
        id
      }
    }
  }
}
""")

struct TweetsList: View {
    let tweets: TweetsList_tweets_Key

    var body: some View {
        RelayFragment(fragment: TweetsList_tweets(), key: tweets, content: Content.init)
    }

    struct Content: View {
        let data: TweetsList_tweets.Data

        typealias Tweet = TweetsList_tweets.Data.TweetGroupConnection_allTweets.TweetGroupEdge_edges.TweetGroup_node
        var tweets: [Tweet] {
            data.allTweets.edges.map { $0.node }
        }

        var body: some View {
            List(tweets, id: \.id) { tweet in
                Text(tweet.id)
            }
        }
    }
}



// TODO get these autogenerated by relay-compiler

enum TweetFilter: String, Codable, CustomStringConvertible {
    case upcoming = "UPCOMING"
    case past = "PAST"

    var description: String {
        return rawValue
    }
}

typealias Cursor = String
