// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package graphql

import (
	"github.com/mjm/courier-js/internal/auth"
	"github.com/mjm/courier-js/internal/billing"
	"github.com/mjm/courier-js/internal/db"
	"github.com/mjm/courier-js/internal/resolvers"
	"github.com/mjm/courier-js/internal/service"
)

// Injectors from wire.go:

func InitializeHandler(schemaString string, authConfig auth.Config, dbConfig db.Config, stripeConfig billing.Config) (*Handler, error) {
	dbDB, err := db.New(dbConfig)
	if err != nil {
		return nil, err
	}
	tweetService := service.NewTweetService(dbDB)
	root := resolvers.New(dbDB, tweetService)
	schema, err := NewSchema(schemaString, root)
	if err != nil {
		return nil, err
	}
	authenticator, err := auth.NewAuthenticator(authConfig)
	if err != nil {
		return nil, err
	}
	api := billing.NewClient(stripeConfig)
	handler := NewHandler(schema, authenticator, dbDB, api)
	return handler, nil
}
