// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package loaders

import (
	"github.com/mjm/courier-js/internal/db"
	"github.com/mjm/courier-js/internal/models/tweet"
)

// Injectors from wire.go:

func CreateLoaders(db2 *db.DB) Loaders {
	loader := tweet.NewLoader(db2)
	loaders := Loaders{
		Tweets: loader,
	}
	return loaders
}
