// Auto-generated by relay-compiler. Do not edit.

import Relay

struct DetailedTweetRow_tweet {
    var fragmentPointer: FragmentPointer

    init(key: DetailedTweetRow_tweet_Key) {
        fragmentPointer = key.fragment_DetailedTweetRow_tweet
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "DetailedTweetRow_tweet",
            type: "Tweet",
            selections: [
                .field(ReaderScalarField(
                    name: "body"
                )),
                .field(ReaderScalarField(
                    name: "mediaURLs"
                ))
            ])
    }
}


extension DetailedTweetRow_tweet {
    struct Data: Decodable {
        var body: String
        var mediaURLs: [String]
    }
}

protocol DetailedTweetRow_tweet_Key {
    var fragment_DetailedTweetRow_tweet: FragmentPointer { get }
}

extension DetailedTweetRow_tweet: Relay.Fragment {}

#if canImport(RelaySwiftUI)

import RelaySwiftUI

extension DetailedTweetRow_tweet_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.FragmentNext<DetailedTweetRow_tweet> {
        RelaySwiftUI.FragmentNext<DetailedTweetRow_tweet>(self)
    }
}

#endif
