// Auto-generated by relay-compiler. Do not edit.

import Relay

struct DetailedTweetActions_tweetGroup {
    var fragmentPointer: FragmentPointer

    init(key: DetailedTweetActions_tweetGroup_Key) {
        fragmentPointer = key.fragment_DetailedTweetActions_tweetGroup
    }

    static var node: ReaderFragment {
        ReaderFragment(
            name: "DetailedTweetActions_tweetGroup",
            type: "TweetGroup",
            selections: [
                .field(ReaderLinkedField(
                    name: "tweets",
                    concreteType: "Tweet",
                    plural: true,
                    selections: [
                        .field(ReaderScalarField(
                            name: "postedTweetID"
                        ))
                    ]
                )),
                .field(ReaderScalarField(
                    name: "id"
                )),
                .field(ReaderScalarField(
                    name: "status"
                )),
                .field(ReaderScalarField(
                    name: "postAfter"
                )),
                .field(ReaderScalarField(
                    name: "postedAt"
                )),
                .field(ReaderScalarField(
                    name: "postedRetweetID"
                ))
            ]
        )
    }
}

extension DetailedTweetActions_tweetGroup {
    struct Data: Decodable, Identifiable {
        var tweets: [Tweet_tweets]
        var id: String
        var status: TweetStatus
        var postAfter: String?
        var postedAt: String?
        var postedRetweetID: String?

        struct Tweet_tweets: Decodable {
            var postedTweetID: String?
        }
    }
}

protocol DetailedTweetActions_tweetGroup_Key {
    var fragment_DetailedTweetActions_tweetGroup: FragmentPointer { get }
}

extension DetailedTweetActions_tweetGroup: Relay.Fragment {}

#if swift(>=5.3) && canImport(RelaySwiftUI)
import RelaySwiftUI

extension DetailedTweetActions_tweetGroup_Key {
    @available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
    func asFragment() -> RelaySwiftUI.FragmentNext<DetailedTweetActions_tweetGroup> {
        RelaySwiftUI.FragmentNext<DetailedTweetActions_tweetGroup>(self)
    }
}
#endif