// Auto-generated by relay-compiler. Do not edit.

import Relay

struct TweetEditedEventQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "TweetEditedEventQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .field(ReaderLinkedField(
                                name: "tweets",
                                concreteType: "Tweet",
                                plural: true,
                                selections: [
                                    .field(ReaderScalarField(
                                        name: "body"
                                    )),
                                    .field(ReaderScalarField(
                                        name: "mediaURLs"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "TweetEditedEventQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationLinkedField(
                                name: "tweets",
                                concreteType: "Tweet",
                                plural: true,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "body"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "mediaURLs"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "TweetEditedEventQuery",
                operationKind: .query,
                text: """
query TweetEditedEventQuery(
  $id: ID!
) {
  tweetGroup(id: $id) {
    id
    tweets {
      body
      mediaURLs
    }
  }
}
"""))
    }
}


extension TweetEditedEventQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }

    init(id: String) {
        self.init(variables: .init(id: id))
    }
}

#if canImport(RelaySwiftUI)

import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
extension RelaySwiftUI.QueryNext.WrappedValue where O == TweetEditedEventQuery {
    func get(id: String, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<TweetEditedEventQuery>.Result {
        self.get(.init(id: id), fetchKey: fetchKey)
    }
}

#endif

extension TweetEditedEventQuery {
    struct Data: Decodable {
        var tweetGroup: TweetGroup_tweetGroup?

        struct TweetGroup_tweetGroup: Decodable, Identifiable {
            var id: String
            var tweets: [Tweet_tweets]

            struct Tweet_tweets: Decodable {
                var body: String
                var mediaURLs: [String]
            }
        }
    }
}

extension TweetEditedEventQuery: Relay.Operation {}
