// Auto-generated by relay-compiler. Do not edit.

import Relay

struct TweetCanceledEventQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "TweetCanceledEventQuery",
                type: "Query",
                selections: [
                    .field(ReaderLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .field(ReaderScalarField(
                                name: "status"
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "TweetCanceledEventQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationScalarField(
                                name: "status"
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "TweetCanceledEventQuery",
                operationKind: .query,
                text: """
query TweetCanceledEventQuery(
  $id: ID!
) {
  tweetGroup(id: $id) {
    id
    status
  }
}
"""))
    }
}


extension TweetCanceledEventQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }

    init(id: String) {
        self.init(variables: .init(id: id))
    }
}

#if canImport(RelaySwiftUI)

import RelaySwiftUI

@available(iOS 14.0, macOS 10.16, tvOS 14.0, watchOS 7.0, *)
extension RelaySwiftUI.QueryNext.WrappedValue where O == TweetCanceledEventQuery {
    func get(id: String, fetchKey: Any? = nil) -> RelaySwiftUI.QueryNext<TweetCanceledEventQuery>.Result {
        self.get(.init(id: id), fetchKey: fetchKey)
    }
}

#endif

extension TweetCanceledEventQuery {
    struct Data: Decodable {
        var tweetGroup: TweetGroup_tweetGroup?

        struct TweetGroup_tweetGroup: Decodable, Identifiable {
            var id: String
            var status: TweetStatus
        }
    }
}

extension TweetCanceledEventQuery: Relay.Operation {}
