// Auto-generated by relay-compiler. Do not edit.

import Relay

struct TweetEditedEventQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "TweetEditedEventQuery",
                selections: [
                    .field(ReaderLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .field(ReaderLinkedField(
                                name: "tweets",
                                concreteType: "Tweet",
                                plural: true,
                                selections: [
                                    .field(ReaderScalarField(
                                        name: "body"
                                    )),
                                    .field(ReaderScalarField(
                                        name: "mediaURLs"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "TweetEditedEventQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationLinkedField(
                                name: "tweets",
                                concreteType: "Tweet",
                                plural: true,
                                selections: [
                                    .field(NormalizationScalarField(
                                        name: "body"
                                    )),
                                    .field(NormalizationScalarField(
                                        name: "mediaURLs"
                                    ))
                                ]
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "TweetEditedEventQuery",
                operationKind: .query,
                text: """
query TweetEditedEventQuery(
  $id: ID!
) {
  tweetGroup(id: $id) {
    id
    tweets {
      body
      mediaURLs
    }
  }
}
"""))
    }
}


extension TweetEditedEventQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }
}

extension TweetEditedEventQuery {
    struct Data: Readable {
        var tweetGroup: TweetGroup_tweetGroup?

        init(from data: SelectorData) {
            tweetGroup = data.get(TweetGroup_tweetGroup?.self, "tweetGroup")
        }

        struct TweetGroup_tweetGroup: Readable {
            var id: String
            var tweets: [Tweet_tweets]

            init(from data: SelectorData) {
                id = data.get(String.self, "id")
                tweets = data.get([Tweet_tweets].self, "tweets")
            }

            struct Tweet_tweets: Readable {
                var body: String
                var mediaURLs: [String]

                init(from data: SelectorData) {
                    body = data.get(String.self, "body")
                    mediaURLs = data.get([String].self, "mediaURLs")
                }
            }
        }
    }
}

extension TweetEditedEventQuery: Relay.Operation {}
