// Auto-generated by relay-compiler. Do not edit.

import Relay

struct TweetCanceledEventQuery {
    var variables: Variables

    init(variables: Variables) {
        self.variables = variables
    }

    static var node: ConcreteRequest {
        ConcreteRequest(
            fragment: ReaderFragment(
                name: "TweetCanceledEventQuery",
                selections: [
                    .field(ReaderLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(ReaderScalarField(
                                name: "id"
                            )),
                            .field(ReaderScalarField(
                                name: "status"
                            ))
                        ]
                    ))
                ]),
            operation: NormalizationOperation(
                name: "TweetCanceledEventQuery",
                selections: [
                    .field(NormalizationLinkedField(
                        name: "tweetGroup",
                        args: [
                            VariableArgument(name: "id", variableName: "id")
                        ],
                        concreteType: "TweetGroup",
                        plural: false,
                        selections: [
                            .field(NormalizationScalarField(
                                name: "id"
                            )),
                            .field(NormalizationScalarField(
                                name: "status"
                            ))
                        ]
                    ))
                ]),
            params: RequestParameters(
                name: "TweetCanceledEventQuery",
                operationKind: .query,
                text: """
query TweetCanceledEventQuery(
  $id: ID!
) {
  tweetGroup(id: $id) {
    id
    status
  }
}
"""))
    }
}


extension TweetCanceledEventQuery {
    struct Variables: VariableDataConvertible {
        var id: String

        var variableData: VariableData {
            [
                "id": id,
            ]
        }
    }
}

extension TweetCanceledEventQuery {
    struct Data: Readable {
        var tweetGroup: TweetGroup_tweetGroup?

        init(from data: SelectorData) {
            tweetGroup = data.get(TweetGroup_tweetGroup?.self, "tweetGroup")
        }

        struct TweetGroup_tweetGroup: Readable {
            var id: String
            var status: TweetStatus

            init(from data: SelectorData) {
                id = data.get(String.self, "id")
                status = data.get(TweetStatus.self, "status")
            }
        }
    }
}

extension TweetCanceledEventQuery: Relay.Operation {}
