import React from "react"
import Link from "next/link"
import Head from "../components/head"
import withDefaultPage from "../hocs/defaultPage"
import Router from "next/router"
import { Card, Text, Box, Heading } from "@rebass/emotion"
import Group from "../components/group"
import { Button } from "../components/button"
import { NextPage } from "next"

const Home: NextPage<{}> = () => {
  return (
    <Box>
      <Head title="Courier" />

      <Card mb={4} px={4} py={5} bg="white" boxShadow="md">
        <Heading
          as="h1"
          fontSize={6}
          fontWeight={500}
          mb={2}
          color="primary.900"
        >
          Courier delivers your microblog to Twitter
        </Heading>
        <Text
          as="h2"
          fontFamily="body"
          fontSize={4}
          fontWeight={400}
          mt={3}
          mb={4}
          lineHeight="normal"
        >
          Post everything to your own blog, and let Courier deliver it to
          Twitter in a way that makes sense.
        </Text>

        <Link href="/login" passHref>
          <Button as="a" size="large">
            Get Started
          </Button>
        </Link>
      </Card>

      <Card px={4} mb={4}>
        <Text fontSize={3} lineHeight="normal">
          You don’t have to leave Twitter behind to be able to own your content.
          Write all your posts, from shower thoughts to long-form essays, on
          your own site, and let Courier handle bringing it to Twitter.
        </Text>
      </Card>

      <Box px={4}>
        <Group direction="row" spacing={4}>
          <FeatureCard title="Translates your HTML into tweetable text">
            Courier understands what a tweet should look like and will format
            your posts in an intelligent way. Your tweets will look like you
            typed them by hand just for Twitter.
          </FeatureCard>
          <FeatureCard title="Edit your tweets before they go public">
            Optionally review drafts of your autogenerated tweets before they
            get posted. You can catch typos and translation mistakes before they
            go public, or decide you didn’t want to tweet that post after all.
          </FeatureCard>
          <FeatureCard title="Pull content from multiple feeds">
            Courier can watch many different feeds and post them all to the same
            Twitter account. You can set some feeds to post automatically after
            a short delay while having other feeds require your approval before
            posting.
          </FeatureCard>
        </Group>
      </Box>
    </Box>
  )
}

Home.getInitialProps = async ({ res, ...ctx }) => {
  if (!(ctx as any).user) {
    return {}
  }

  if (res) {
    res.writeHead(302, { Location: "/tweets" })
    res.end()
  } else {
    Router.push("/tweets")
  }

  return {}
}

export default withDefaultPage(Home)

const FeatureCard = (props: { title: string; children: React.ReactNode }) => (
  <Card width={1 / 3}>
    <Heading as="h3" fontWeight={500} mb={2} color="primary.900">
      {props.title}
    </Heading>
    <Text lineHeight="normal">{props.children}</Text>
  </Card>
)
