// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pusherauth

import (
	"github.com/mjm/courier-js/internal/auth"
	"github.com/mjm/courier-js/internal/event"
	"github.com/mjm/courier-js/internal/secret"
	"github.com/mjm/courier-js/internal/trace"
)

// Injectors from wire.go:

func InitializeHandler(gcpConfig secret.GCPConfig) (*Handler, error) {
	client, err := secret.NewSecretManager(gcpConfig)
	if err != nil {
		return nil, err
	}
	gcpSecretKeeper := secret.NewGCPSecretKeeper(gcpConfig, client)
	config, err := trace.NewConfigFromSecrets(gcpSecretKeeper)
	if err != nil {
		return nil, err
	}
	authConfig, err := auth.NewConfigFromSecrets(gcpSecretKeeper)
	if err != nil {
		return nil, err
	}
	management, err := auth.NewManagementClient(authConfig)
	if err != nil {
		return nil, err
	}
	jwksClient := auth.NewJWKSClient(authConfig)
	authenticator := auth.NewAuthenticator(authConfig, management, jwksClient)
	pusherClient, err := event.NewPusherClient(gcpSecretKeeper)
	if err != nil {
		return nil, err
	}
	handler := NewHandler(config, authenticator, pusherClient)
	return handler, nil
}
