// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pusherauth

import (
	"github.com/mjm/courier-js/internal/auth"
	"github.com/mjm/courier-js/internal/config"
	"github.com/mjm/courier-js/internal/event"
	"github.com/mjm/courier-js/internal/secret"
	"github.com/mjm/courier-js/internal/trace"
)

// Injectors from wire.go:

func InitializeHandler(gcpConfig secret.GCPConfig) (*Handler, error) {
	client, err := secret.NewSecretManager(gcpConfig)
	if err != nil {
		return nil, err
	}
	gcpSecretKeeper := secret.NewGCPSecretKeeper(gcpConfig, client)
	traceConfig, err := trace.NewConfigFromSecrets(gcpSecretKeeper)
	if err != nil {
		return nil, err
	}
	defaultEnv := &config.DefaultEnv{}
	loader := config.NewLoader(defaultEnv, gcpSecretKeeper)
	authConfig, err := auth.NewConfig(loader)
	if err != nil {
		return nil, err
	}
	management, err := auth.NewManagementClient(authConfig)
	if err != nil {
		return nil, err
	}
	jwksClient := auth.NewJWKSClient(authConfig)
	authenticator := auth.NewAuthenticator(authConfig, management, jwksClient)
	pusherClient, err := event.NewPusherClient(gcpSecretKeeper)
	if err != nil {
		return nil, err
	}
	pushNotifications, err := event.NewBeamsClient(gcpSecretKeeper)
	if err != nil {
		return nil, err
	}
	handler := NewHandler(traceConfig, authenticator, pusherClient, pushNotifications)
	return handler, nil
}
