// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

package tweets

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TweetCanceled struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId              string   `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetCanceled) Reset()         { *m = TweetCanceled{} }
func (m *TweetCanceled) String() string { return proto.CompactTextString(m) }
func (*TweetCanceled) ProtoMessage()    {}
func (*TweetCanceled) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{0}
}

func (m *TweetCanceled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetCanceled.Unmarshal(m, b)
}
func (m *TweetCanceled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetCanceled.Marshal(b, m, deterministic)
}
func (m *TweetCanceled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetCanceled.Merge(m, src)
}
func (m *TweetCanceled) XXX_Size() int {
	return xxx_messageInfo_TweetCanceled.Size(m)
}
func (m *TweetCanceled) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetCanceled.DiscardUnknown(m)
}

var xxx_messageInfo_TweetCanceled proto.InternalMessageInfo

func (m *TweetCanceled) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TweetCanceled) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

type TweetUncanceled struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId              string   `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetUncanceled) Reset()         { *m = TweetUncanceled{} }
func (m *TweetUncanceled) String() string { return proto.CompactTextString(m) }
func (*TweetUncanceled) ProtoMessage()    {}
func (*TweetUncanceled) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{1}
}

func (m *TweetUncanceled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetUncanceled.Unmarshal(m, b)
}
func (m *TweetUncanceled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetUncanceled.Marshal(b, m, deterministic)
}
func (m *TweetUncanceled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetUncanceled.Merge(m, src)
}
func (m *TweetUncanceled) XXX_Size() int {
	return xxx_messageInfo_TweetUncanceled.Size(m)
}
func (m *TweetUncanceled) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetUncanceled.DiscardUnknown(m)
}

var xxx_messageInfo_TweetUncanceled proto.InternalMessageInfo

func (m *TweetUncanceled) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TweetUncanceled) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

type TweetEdited struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId              string   `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetEdited) Reset()         { *m = TweetEdited{} }
func (m *TweetEdited) String() string { return proto.CompactTextString(m) }
func (*TweetEdited) ProtoMessage()    {}
func (*TweetEdited) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{2}
}

func (m *TweetEdited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetEdited.Unmarshal(m, b)
}
func (m *TweetEdited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetEdited.Marshal(b, m, deterministic)
}
func (m *TweetEdited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetEdited.Merge(m, src)
}
func (m *TweetEdited) XXX_Size() int {
	return xxx_messageInfo_TweetEdited.Size(m)
}
func (m *TweetEdited) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetEdited.DiscardUnknown(m)
}

var xxx_messageInfo_TweetEdited proto.InternalMessageInfo

func (m *TweetEdited) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TweetEdited) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

type TweetPosted struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId              string   `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	Autoposted           bool     `protobuf:"varint,3,opt,name=autoposted,proto3" json:"autoposted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetPosted) Reset()         { *m = TweetPosted{} }
func (m *TweetPosted) String() string { return proto.CompactTextString(m) }
func (*TweetPosted) ProtoMessage()    {}
func (*TweetPosted) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{3}
}

func (m *TweetPosted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetPosted.Unmarshal(m, b)
}
func (m *TweetPosted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetPosted.Marshal(b, m, deterministic)
}
func (m *TweetPosted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetPosted.Merge(m, src)
}
func (m *TweetPosted) XXX_Size() int {
	return xxx_messageInfo_TweetPosted.Size(m)
}
func (m *TweetPosted) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetPosted.DiscardUnknown(m)
}

var xxx_messageInfo_TweetPosted proto.InternalMessageInfo

func (m *TweetPosted) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TweetPosted) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

func (m *TweetPosted) GetAutoposted() bool {
	if m != nil {
		return m.Autoposted
	}
	return false
}

type TweetsImported struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId       string   `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	CreatedTweetIds      []string `protobuf:"bytes,3,rep,name=created_tweet_ids,json=createdTweetIds,proto3" json:"created_tweet_ids,omitempty"`
	UpdatedTweetIds      []string `protobuf:"bytes,4,rep,name=updated_tweet_ids,json=updatedTweetIds,proto3" json:"updated_tweet_ids,omitempty"`
	Autopost             bool     `protobuf:"varint,5,opt,name=autopost,proto3" json:"autopost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetsImported) Reset()         { *m = TweetsImported{} }
func (m *TweetsImported) String() string { return proto.CompactTextString(m) }
func (*TweetsImported) ProtoMessage()    {}
func (*TweetsImported) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f22242cb04491f9, []int{4}
}

func (m *TweetsImported) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetsImported.Unmarshal(m, b)
}
func (m *TweetsImported) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetsImported.Marshal(b, m, deterministic)
}
func (m *TweetsImported) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetsImported.Merge(m, src)
}
func (m *TweetsImported) XXX_Size() int {
	return xxx_messageInfo_TweetsImported.Size(m)
}
func (m *TweetsImported) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetsImported.DiscardUnknown(m)
}

var xxx_messageInfo_TweetsImported proto.InternalMessageInfo

func (m *TweetsImported) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TweetsImported) GetSubscriptionId() string {
	if m != nil {
		return m.SubscriptionId
	}
	return ""
}

func (m *TweetsImported) GetCreatedTweetIds() []string {
	if m != nil {
		return m.CreatedTweetIds
	}
	return nil
}

func (m *TweetsImported) GetUpdatedTweetIds() []string {
	if m != nil {
		return m.UpdatedTweetIds
	}
	return nil
}

func (m *TweetsImported) GetAutopost() bool {
	if m != nil {
		return m.Autopost
	}
	return false
}

func init() {
	proto.RegisterType((*TweetCanceled)(nil), "courier.events.tweets.TweetCanceled")
	proto.RegisterType((*TweetUncanceled)(nil), "courier.events.tweets.TweetUncanceled")
	proto.RegisterType((*TweetEdited)(nil), "courier.events.tweets.TweetEdited")
	proto.RegisterType((*TweetPosted)(nil), "courier.events.tweets.TweetPosted")
	proto.RegisterType((*TweetsImported)(nil), "courier.events.tweets.TweetsImported")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor_8f22242cb04491f9) }

var fileDescriptor_8f22242cb04491f9 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x02, 0x69, 0x7a, 0x40, 0x23, 0x2c, 0x21, 0x02, 0x03, 0x8a, 0xb2, 0x10, 0x31,
	0x74, 0xe1, 0x17, 0x40, 0xd5, 0x21, 0x1b, 0x8a, 0xca, 0xc2, 0x52, 0xa5, 0xf6, 0x0d, 0x96, 0x20,
	0xb6, 0x7c, 0x36, 0xfc, 0x43, 0x7e, 0x17, 0xca, 0x25, 0x2d, 0x15, 0x03, 0x43, 0xd9, 0x72, 0xf7,
	0x5e, 0xbe, 0xf7, 0x2c, 0x1d, 0x9c, 0xe1, 0x07, 0x76, 0x9e, 0xe6, 0xd6, 0x19, 0x6f, 0xc4, 0xa5,
	0x34, 0xc1, 0x69, 0x74, 0xf3, 0x71, 0xeb, 0x3f, 0x11, 0x3d, 0x95, 0x0b, 0x38, 0x5f, 0xf5, 0x5f,
	0x8b, 0xb6, 0x93, 0xf8, 0x86, 0x4a, 0x5c, 0xc1, 0x24, 0x10, 0xba, 0xb5, 0x56, 0x79, 0x54, 0x44,
	0xd5, 0xb4, 0x49, 0xfa, 0xb1, 0x56, 0xe2, 0x1a, 0x52, 0xfe, 0xa7, 0x57, 0x8e, 0x58, 0x99, 0xf0,
	0x5c, 0xab, 0x72, 0x09, 0x19, 0x43, 0x5e, 0x3a, 0xf9, 0x1f, 0xcc, 0x23, 0x9c, 0x32, 0x66, 0xa9,
	0xb4, 0x3f, 0x10, 0xd1, 0x8e, 0x88, 0x67, 0x43, 0x07, 0x22, 0xc4, 0x2d, 0x40, 0x1b, 0xbc, 0xb1,
	0x4c, 0xc8, 0xe3, 0x22, 0xaa, 0xd2, 0x66, 0x6f, 0x53, 0x7e, 0x45, 0x30, 0xe3, 0x0c, 0xaa, 0xdf,
	0xad, 0x71, 0x7f, 0xc6, 0xdc, 0x41, 0x46, 0x61, 0x43, 0xd2, 0x69, 0xeb, 0xb5, 0xe9, 0x7e, 0xd2,
	0x66, 0xfb, 0xeb, 0x5a, 0x89, 0x7b, 0xb8, 0x90, 0x0e, 0x5b, 0x8f, 0x6a, 0xbd, 0xed, 0x45, 0x79,
	0x5c, 0xc4, 0xd5, 0xb4, 0xc9, 0x46, 0x61, 0x35, 0xf4, 0xa3, 0xde, 0x1b, 0xac, 0xfa, 0xe5, 0x3d,
	0x1e, 0xbc, 0xa3, 0xb0, 0xf3, 0xde, 0x40, 0xba, 0xad, 0x9e, 0x9f, 0xf0, 0x53, 0x76, 0xf3, 0x53,
	0xfa, 0x9a, 0x0c, 0x47, 0xb0, 0x49, 0xf8, 0x44, 0x1e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x15,
	0x20, 0x4e, 0xe6, 0x32, 0x02, 0x00, 0x00,
}
