// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tasks.proto

package tweets

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostTweetTask struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TweetId              string   `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	Autopost             bool     `protobuf:"varint,3,opt,name=autopost,proto3" json:"autopost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTweetTask) Reset()         { *m = PostTweetTask{} }
func (m *PostTweetTask) String() string { return proto.CompactTextString(m) }
func (*PostTweetTask) ProtoMessage()    {}
func (*PostTweetTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3834c8ef8464a3f, []int{0}
}

func (m *PostTweetTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTweetTask.Unmarshal(m, b)
}
func (m *PostTweetTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTweetTask.Marshal(b, m, deterministic)
}
func (m *PostTweetTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTweetTask.Merge(m, src)
}
func (m *PostTweetTask) XXX_Size() int {
	return xxx_messageInfo_PostTweetTask.Size(m)
}
func (m *PostTweetTask) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTweetTask.DiscardUnknown(m)
}

var xxx_messageInfo_PostTweetTask proto.InternalMessageInfo

func (m *PostTweetTask) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PostTweetTask) GetTweetId() string {
	if m != nil {
		return m.TweetId
	}
	return ""
}

func (m *PostTweetTask) GetAutopost() bool {
	if m != nil {
		return m.Autopost
	}
	return false
}

func init() {
	proto.RegisterType((*PostTweetTask)(nil), "courier.tweets.PostTweetTask")
}

func init() { proto.RegisterFile("tasks.proto", fileDescriptor_b3834c8ef8464a3f) }

var fileDescriptor_b3834c8ef8464a3f = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x49, 0x2c, 0xce,
	0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0xce, 0x2f, 0x2d, 0xca, 0x4c, 0x2d,
	0xd2, 0x2b, 0x29, 0x4f, 0x4d, 0x2d, 0x29, 0x56, 0x8a, 0xe7, 0xe2, 0x0d, 0xc8, 0x2f, 0x2e, 0x09,
	0x01, 0xf1, 0x42, 0x12, 0x8b, 0xb3, 0x85, 0xc4, 0xb9, 0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0xe2, 0x33,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x49, 0x2e,
	0x0e, 0xb0, 0x1e, 0x90, 0x0c, 0x13, 0x58, 0x86, 0x1d, 0xcc, 0xf7, 0x4c, 0x11, 0x92, 0xe2, 0xe2,
	0x48, 0x2c, 0x2d, 0xc9, 0x2f, 0xc8, 0x2f, 0x2e, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x08, 0x82,
	0xf3, 0x9d, 0x38, 0xa2, 0xd8, 0x20, 0x56, 0x25, 0xb1, 0x81, 0x5d, 0x60, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0x5d, 0x08, 0xa1, 0x90, 0x00, 0x00, 0x00,
}
